source 'https://rubygems.org'

gem 'rails'
gem 'sqlite3'
gem 'jbuilder'
gem 'bcrypt'
gem 'autoprefixer-rails'
gem 'multi_json'
gem 'mysql2'

gem 'responders'

gem 'sdoc', group: :doc

group :development do
  gem 'spring'
  gem 'rspec-rails'
end
