source 'https://rubygems.org'

gem 'bcrypt'
gem 'devise'
gem 'jbuilder'
gem 'jwt'
gem 'multi_json'
gem 'mysql2'
gem 'rails'
gem 'responders'
gem 'sqlite3'

gem 'sdoc', group: :doc

group :development do
  gem 'spring'
  gem 'rspec-rails'
end
